### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by lane66** [bayraktar1/SRA-Data-Collector#3]
I used this command during installation：
 snakemake -s workflow/metadata.smk --executor slurm -j 20 --default-resources slurm_account=dla_mm slurm_partition=cpu --use-conda --conda-frontend mamba --latency-wait 60 --printshellcmds

But encountered the following error：
snakemake: error: argument --executor/-e: invalid choice: 'slurm' (choose from 'local', 'dryrun', 'touch')

**Comment by bayraktar1** [comment]
Hi @lane66,

The documentation showed an example of running the pipeline on an HPC with the SLURM scheduler. I have updated the documentation to be more general and added an example of running the pipeline locally. Please refer to the updated documentation.

**Comment by lane66** [comment]
Thank you for your reply! I understand.
